import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'game_models.dart';
import '../../shared/services/audio_manager.dart';

// Sample questions database
// Sample questions database — Hindi/Hinglish Brain Trap riddles
final List<Question> _allQuestions = [
    Question(
    id: 'ea_1',
    question: 'Second wale ko overtake karo, tum kya banoge?',
    options: ['First', 'Second', 'Third', 'Last'],
    correctIndex: 1,
    explanation: 'Tum second ban jaoge, woh third!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_2',
    question: '1 kilo loha ya kapas, zyada bhaari?',
    options: ['Loha', 'Kapas', 'Dono same', 'Pata nahi'],
    correctIndex: 2,
    explanation: 'Dono ka wajan same hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_3',
    question: '2 seb lo, kitne seb paas honge?',
    options: ['1', '2', '3', '0'],
    correctIndex: 1,
    explanation: 'Liye toh 2 hi hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_4',
    question: 'Murga anda kis taraf deta hai?',
    options: ['Left', 'Right', 'Deta hi nahi', 'Upar'],
    correctIndex: 2,
    explanation: 'Murgi deti hai, murga nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_5',
    question: 'Paani peete hi kaunsi cheez mar jaati?',
    options: ['Paudha', 'Aag', 'Macchi', 'Kapda'],
    correctIndex: 1,
    explanation: 'Paani se aag bujh jaati hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_6',
    question: 'River Bank mein paise kyu nahi milte?',
    options: ['Closed hai', 'Yeh nadi ka kinara hai', 'Cheap hai', 'Galat bank'],
    correctIndex: 1,
    explanation: 'River bank nadi ka kinara hota hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_7',
    question: 'World Cup kyu nahi piya ja sakta?',
    options: ['Bahut bada', 'Trophy hai, drink nahi', 'Kadwa hai', 'Mehnga hai'],
    correctIndex: 1,
    explanation: 'World Cup ek trophy hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_8',
    question: '5 log room mein, 2 gaye. Kitne bache?',
    options: ['2', '3', '5', '0'],
    correctIndex: 1,
    explanation: '5-2=3!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_9',
    question: 'Mushroom room mein kyu nahi reh sakte?',
    options: ['Bahut chhota', 'Yeh sabzi hai', 'Darawana hai', 'Mehnga hai'],
    correctIndex: 1,
    explanation: 'Mushroom ek sabzi hai, kamra nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_10',
    question: 'Electric train se dhuaan kahan jaata hai?',
    options: ['Upar', 'Neeche', 'Hota hi nahi', 'Side'],
    correctIndex: 2,
    explanation: 'Electric train mein dhuaan hota hi nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_11',
    question: 'Anpadh phal kaunsa hai?',
    options: ['Aam', 'Anpadh phal', 'Seb', 'Kela'],
    correctIndex: 1,
    explanation: 'Wordplay - jo padh nahi sakta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_12',
    question: 'Bina engine kya khud chalta hai?',
    options: ['Car', 'Nadi', 'Train', 'Bike'],
    correctIndex: 1,
    explanation: 'Nadi khud bahti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_13',
    question: 'Ek ghante mein kitne minute?',
    options: ['100', '60', '50', '120'],
    correctIndex: 1,
    explanation: '60 minute!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_14',
    question: 'India ki rajdhani?',
    options: ['Mumbai', 'Delhi', 'Kolkata', 'Chennai'],
    correctIndex: 1,
    explanation: 'Delhi hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_15',
    question: 'Suraj kis disha se nikalta hai?',
    options: ['Paschim', 'Purab', 'Uttar', 'Dakshin'],
    correctIndex: 1,
    explanation: 'Purab se!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_16',
    question: 'Saal mein kitne mahine?',
    options: ['10', '11', '12', '13'],
    correctIndex: 2,
    explanation: '12 mahine!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_17',
    question: 'Doodh kaun deta hai?',
    options: ['Sher', 'Gaay', 'Kutta', 'Bandar'],
    correctIndex: 1,
    explanation: 'Gaay doodh deti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_18',
    question: 'Insaan ke kitne haath?',
    options: ['1', '2', '3', '4'],
    correctIndex: 1,
    explanation: '2 haath!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_19',
    question: 'Hafte mein kitne din?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: '7 din!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_20',
    question: 'Din mein aasman ka rang?',
    options: ['Lal', 'Neela', 'Hara', 'Kaala'],
    correctIndex: 1,
    explanation: 'Neela!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_21',
    question: '2 + 2 kitna?',
    options: ['3', '4', '5', '22'],
    correctIndex: 1,
    explanation: '4!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_22',
    question: 'Sabse lamba jaanwar?',
    options: ['Haathi', 'Giraffe', 'Sher', 'Bandar'],
    correctIndex: 1,
    explanation: 'Giraffe!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_23',
    question: 'Barfi kis se banti?',
    options: ['Doodh', 'Paani', 'Hawa', 'Mitti'],
    correctIndex: 0,
    explanation: 'Doodh se!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_24',
    question: 'Ek dozen mein kitne?',
    options: ['10', '12', '15', '20'],
    correctIndex: 1,
    explanation: '12!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_25',
    question: 'Sabse chhota mahina (din se)?',
    options: ['January', 'February', 'March', 'April'],
    correctIndex: 1,
    explanation: 'February!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_26',
    question: 'Cricket team mein players?',
    options: ['9', '10', '11', '12'],
    correctIndex: 2,
    explanation: '11 players!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_27',
    question: 'Pani ka formula?',
    options: ['CO2', 'H2O', 'O2', 'NaCl'],
    correctIndex: 1,
    explanation: 'H2O!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_28',
    question: 'Insaan kitni aankhon se dekhta?',
    options: ['1', '2', '3', '4'],
    correctIndex: 1,
    explanation: '2 aankhein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_29',
    question: 'Diwali kis season mein?',
    options: ['Garmi', 'Sardi', 'Barsaat', 'Basant'],
    correctIndex: 1,
    explanation: 'Sardiyon mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_30',
    question: 'Chand kab dikhta hai?',
    options: ['Din', 'Raat', 'Subah', 'Dopahar'],
    correctIndex: 1,
    explanation: 'Raat mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_31',
    question: 'Lal fruit kaunsa hai?',
    options: ['Kela', 'Seb', 'Angoor', 'Aam'],
    correctIndex: 1,
    explanation: 'Seb!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_32',
    question: 'Pencil se kya kaam?',
    options: ['Khana', 'Likhna', 'Sona', 'Daudna'],
    correctIndex: 1,
    explanation: 'Likhna!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_33',
    question: 'Ek minute mein second?',
    options: ['30', '60', '100', '50'],
    correctIndex: 1,
    explanation: '60 second!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_34',
    question: 'Bird ka Hindi matlab?',
    options: ['Machhli', 'Chidiya', 'Kutta', 'Billi'],
    correctIndex: 1,
    explanation: 'Chidiya!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'ea_35',
    question: 'Doosre number par koi cross kare, woh kya banega?',
    options: ['First', 'Third', 'Last', 'Second'],
    correctIndex: 0,
    explanation: 'Cross karne wala first ban jaata hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'me_1',
    question: '100 se 10 kitni baar ghata sakte?',
    options: ['10 baar', 'Ek baar', '100 baar', '5 baar'],
    correctIndex: 1,
    explanation: 'Pehli baar ke baad 90 bachta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_2',
    question: 'Toot ke kaunsi cheez kaam aati?',
    options: ['Glass', 'Anda', 'Plate', 'Phone'],
    correctIndex: 1,
    explanation: 'Anda todna padta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_3',
    question: 'Bharne se halki ho jaaye?',
    options: ['Bottle', 'Bag', 'Balloon', 'Box'],
    correctIndex: 2,
    explanation: 'Gas se balloon udta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_4',
    question: 'Nikalo toh badi hoti jaaye?',
    options: ['Rassi', 'Gaddha', 'Cake', 'Roti'],
    correctIndex: 1,
    explanation: 'Mitti nikalne se gaddha badhta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_5',
    question: 'Geeli hokar bhi sukhaati hai?',
    options: ['Pani', 'Towel', 'Sponge', 'Cloth'],
    correctIndex: 1,
    explanation: 'Towel khud geela hokar sukhaata hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_6',
    question: 'Bina bole jawab deti hai?',
    options: ['Phone', 'Echo', 'Radio', 'TV'],
    correctIndex: 1,
    explanation: 'Echo awaaz wapas karta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_7',
    question: 'Aankh hai par dekh nahi sakti?',
    options: ['Sui', 'Camera', 'Doll', 'Glasses'],
    correctIndex: 0,
    explanation: 'Sui ki aankh sirf dhaaga ke liye!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_8',
    question: 'Gardan hai par sir nahi?',
    options: ['Bottle', 'Doll', 'Shirt', 'Necklace'],
    correctIndex: 0,
    explanation: 'Bottle ki gardan hoti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_9',
    question: 'Daant hain par kaat nahi sakti?',
    options: ['Aara', 'Kanghi', 'Chaaku', 'Kainchi'],
    correctIndex: 1,
    explanation: 'Kanghi baal sulajhati hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_10',
    question: 'Pair hain par chal nahi sakti?',
    options: ['Insaan', 'Table', 'Ghoda', 'Robot'],
    correctIndex: 1,
    explanation: 'Table ke pair hote hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_11',
    question: 'Machhli geeli hogi baarish mein?',
    options: ['Haan', 'Pehle se geeli hai', 'Pata nahi', 'Thodi si'],
    correctIndex: 1,
    explanation: 'Machhli pehle se hi geeli hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_12',
    question: 'Bina pankh udti hai?',
    options: ['Patang', 'Samay', 'Gubbara', 'Pakshi'],
    correctIndex: 1,
    explanation: 'Samay udta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_13',
    question: 'Upar jaaye, neeche na aaye?',
    options: ['Gend', 'Umar', 'Patang', 'Rocket'],
    correctIndex: 1,
    explanation: 'Umar sirf badhti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_14',
    question: 'Chale jitna, utni kam ho?',
    options: ['Pencil', 'Mombatti', 'Soap', 'Eraser'],
    correctIndex: 1,
    explanation: 'Mombatti jal jal ke chhoti hoti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_15',
    question: 'Birthday har saal nahi aata, kyu?',
    options: ['Fake hai', '29 February hai', 'Bhool jaata', 'Calendar galat'],
    correctIndex: 1,
    explanation: '29 February sirf leap year mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_16',
    question: 'Saaf karo, kaali ho jaaye?',
    options: ['Mirror', 'Blackboard', 'Glass', 'Table'],
    correctIndex: 1,
    explanation: 'Blackboard saaf karne se kaala dikhta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_17',
    question: 'Chalti nahi par time batati?',
    options: ['Clock', 'Calendar', 'Phone', 'Watch'],
    correctIndex: 1,
    explanation: 'Calendar din-mahina batata hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_18',
    question: 'Rang nahi par dikh jaaye?',
    options: ['Hawa', 'Dhuaan', 'Paani', 'Roshni'],
    correctIndex: 1,
    explanation: 'Dhuaan bina rang ke dikhta hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_19',
    question: 'Bina zubaan bolti hai?',
    options: ['Tota', 'Ghanti', 'Radio', 'Phone'],
    correctIndex: 1,
    explanation: 'Ghanti bajti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_20',
    question: 'Khane ko kharido, khaate nahi?',
    options: ['Roti', 'Plate', 'Sabzi', 'Chawal'],
    correctIndex: 1,
    explanation: 'Plate mein khaana parosa jaata!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_21',
    question: 'Dil hai par dhadakta nahi?',
    options: ['Insaan', 'Cards ka Heart', 'Robot', 'Jaanwar'],
    correctIndex: 1,
    explanation: 'Cards ke heart mein dhadkan nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_22',
    question: 'Sabse bada samundar?',
    options: ['Arabian Sea', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean'],
    correctIndex: 1,
    explanation: 'Pacific Ocean sabse bada!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_23',
    question: 'Surya ke sabse paas graha?',
    options: ['Mangal', 'Budh', 'Shukra', 'Prithvi'],
    correctIndex: 1,
    explanation: 'Budh (Mercury) sabse paas!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_24',
    question: 'Sharir mein kitni haddiyan?',
    options: ['106', '206', '306', '406'],
    correctIndex: 1,
    explanation: '206 haddiyan!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_25',
    question: 'Shahad kaun banata hai?',
    options: ['Makhi', 'Madhumakhi', 'Titli', 'Machhar'],
    correctIndex: 1,
    explanation: 'Madhumakhi shahad banati hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_26',
    question: 'Taj Mahal kahan hai?',
    options: ['Delhi', 'Agra', 'Jaipur', 'Lucknow'],
    correctIndex: 1,
    explanation: 'Agra mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_27',
    question: 'Sabse halki dhaatu?',
    options: ['Loha', 'Sona', 'Lithium', 'Tamba'],
    correctIndex: 2,
    explanation: 'Lithium sabse halki!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_28',
    question: 'ODI mein kitne overs?',
    options: ['20', '50', '40', '60'],
    correctIndex: 1,
    explanation: '50 overs!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_29',
    question: 'Registan ka jaanwar?',
    options: ['Penguin', 'Camel', 'Polar Bear', 'Seal'],
    correctIndex: 1,
    explanation: 'Camel/Unt!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_30',
    question: 'Dil ek minute mein dhadke?',
    options: ['20', '72', '200', '500'],
    correctIndex: 1,
    explanation: 'Average 72 dhadkan!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_31',
    question: 'India ki sabse lambi nadi?',
    options: ['Yamuna', 'Ganga', 'Godavari', 'Narmada'],
    correctIndex: 1,
    explanation: 'Ganga!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_32',
    question: 'Aag bujhane ko kya use karein?',
    options: ['Tel', 'Paani', 'Petrol', 'Gas'],
    correctIndex: 1,
    explanation: 'Paani aag bujhata hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_33',
    question: 'Sabse jyada heat absorb karta color?',
    options: ['White', 'Black', 'Yellow', 'Blue'],
    correctIndex: 1,
    explanation: 'Black sabse zyada absorb karta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_34',
    question: 'Olympics kitne saal mein?',
    options: ['2', '4', '6', '8'],
    correctIndex: 1,
    explanation: 'Har 4 saal mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'me_35',
    question: 'Subah khile, shaam muraajhaye?',
    options: ['Patta', 'Phool', 'Ghaas', 'Ped'],
    correctIndex: 1,
    explanation: 'Kuch phool aise hote hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'ha_1',
    question: 'Chaabi hai par tala nahi?',
    options: ['Door', 'Keyboard', 'Locker', 'Safe'],
    correctIndex: 1,
    explanation: 'Keyboard ki keys hoti hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_2',
    question: 'Muh hai par khaata nahi?',
    options: ['Insaan', 'Nadi', 'Bottle', 'Jaanwar'],
    correctIndex: 1,
    explanation: 'Nadi ka muh samundra mein!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_3',
    question: 'Kal Sunday hai, aaj kya?',
    options: ['Friday', 'Saturday', 'Sunday', 'Monday'],
    correctIndex: 0,
    explanation: 'Kal Sunday matlab aaj Friday!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_4',
    question: '3 goli, 30 min gap, kitne time mein khatam?',
    options: ['1.5 Hour', '1 Hour', '90 min', '2 Hour'],
    correctIndex: 1,
    explanation: 'Pehli abhi, 1 hour mein khatam!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_5',
    question: 'Saamne hai par dikhti nahi?',
    options: ['Past', 'Future', 'Hawa', 'Khushi'],
    correctIndex: 1,
    explanation: 'Future hamesha aage hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_6',
    question: 'Hamesha aaye, kabhi na aaye?',
    options: ['Aaj', 'Kal', 'Bahar', 'Andar'],
    correctIndex: 1,
    explanation: 'Kal kabhi nahi aata!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_7',
    question: '8 din bina soye kaise raha?',
    options: ['Coffee piya', 'Raat ko sota tha', 'Pill khayi', 'Yoga kiya'],
    correctIndex: 1,
    explanation: 'Raat mein sota tha!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_8',
    question: 'Wajan nahi par pakad nahi sakte?',
    options: ['Hawa', 'Saans', 'Paani', 'Dhuaan'],
    correctIndex: 1,
    explanation: 'Saans pakdi nahi ja sakti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_9',
    question: 'Andhere mein bhi saath hoti?',
    options: ['Saaya', 'Tum khud', 'Doston', 'Phone'],
    correctIndex: 1,
    explanation: 'Tum khud hamesha saath ho!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_10',
    question: '10 machhli, 3 mari, kitni bachi?',
    options: ['7', '10', '3', '0'],
    correctIndex: 1,
    explanation: 'Sab paani mein hi hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_11',
    question: 'Toote, awaaz na kare?',
    options: ['Glass', 'Vishwas', 'Plate', 'Mirror'],
    correctIndex: 1,
    explanation: 'Vishwas tootne par awaaz nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_12',
    question: '5 aur 6 seb haath mein, kya hai?',
    options: ['11 seb', 'Bade haath', '5 seb', '6 seb'],
    correctIndex: 1,
    explanation: 'Itna nahi aata, isliye bade haath!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_13',
    question: 'Kheencho, chhoti ho jaaye?',
    options: ['Rassi', 'Cigarette', 'Rubber Band', 'Dhaaga'],
    correctIndex: 1,
    explanation: 'Cigarette puff se chhoti hoti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_14',
    question: 'Kabhi na aaye, kaunsa din?',
    options: ['Aaj', 'Kal', 'Parso', 'Sunday'],
    correctIndex: 1,
    explanation: 'Kal kabhi aata hi nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_15',
    question: 'Kharidne wala use nahi karta?',
    options: ['Gift', 'Kafan', 'Bookcase', 'Toy'],
    correctIndex: 1,
    explanation: 'Kafan khud nahi use karte!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_16',
    question: 'Bechne wala use nahi karta?',
    options: ['Sabzi', 'Kafan', 'Mithai', 'Kapda'],
    correctIndex: 1,
    explanation: 'Kafan bechne wala bhi nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_17',
    question: 'Seedhi se 5th, lift se 1st, kyu?',
    options: ['Exercise ke liye', 'Button nahi pahunchta', 'Lift kharab', 'Pasand hai'],
    correctIndex: 1,
    explanation: 'Chhota hai, button nahi pahunchta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_18',
    question: 'Pencil 5rs, eraser 2rs, 3+2 ka total?',
    options: ['19', '17', '21', '15'],
    correctIndex: 0,
    explanation: '3x5+2x2=19!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_19',
    question: 'Bina haath taali bajati cheez?',
    options: ['Insaan', 'Baarish patton par', 'Tabla', 'Dhol'],
    correctIndex: 1,
    explanation: 'Baarish ki boondein patton par!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_20',
    question: '6 beti, ek hi bhai. Kitne bachhe?',
    options: ['12', '7', '6', '13'],
    correctIndex: 1,
    explanation: 'Sab behnon ka ek bhai - 6+1=7!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_21',
    question: 'Sabko milti, koi kharid nahi sakta?',
    options: ['Paisa', 'Samay', 'Khushi', 'Gyaan'],
    correctIndex: 1,
    explanation: 'Samay kharida nahi ja sakta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_22',
    question: 'Picture dekh kahe meri saas hai - kiski?',
    options: ['Apni', 'Bête ki', 'Pita ki', 'Patni ki'],
    correctIndex: 0,
    explanation: 'Khud ki picture hai yeh!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_23',
    question: 'Purani ho, keemti ho?',
    options: ['Phone', 'Wine', 'Bread', 'Doodh'],
    correctIndex: 1,
    explanation: 'Purani wine zyada keemti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_24',
    question: '1-100 mein 9 kitni baar?',
    options: ['10', '19', '20', '9'],
    correctIndex: 2,
    explanation: '20 baar aata hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_25',
    question: 'Dekho, chhoo nahi sakte?',
    options: ['Pani', 'Reflection', 'Hawa', 'Aag'],
    correctIndex: 1,
    explanation: 'Reflection dekh sakte, chhoo nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_26',
    question: '3 driver, koi nahi chala raha?',
    options: ['Truck khada hai', 'Sab so rahe', 'Auto pilot', 'Truck kharab'],
    correctIndex: 0,
    explanation: 'Truck parked hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_27',
    question: '2 baap 2 bête, 3 machhli, sabko ek-ek?',
    options: ['Baant li', 'Dada-Beta-Pota', 'Chhupayi', 'Pakda nahi'],
    correctIndex: 1,
    explanation: 'Teen generations - 3 log!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_28',
    question: 'Khone par hi keemat pata chale?',
    options: ['Paisa', 'Samay', 'Cheez', 'Sabhi'],
    correctIndex: 3,
    explanation: 'Sab cheezon ki keemat khone par!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_29',
    question: 'Ladki bhai se bada, bhai khud ko bada bole?',
    options: ['Bhai jhooth', 'Twins, bhai pehle paida', 'Ladki choti', 'Confusion'],
    correctIndex: 1,
    explanation: 'Twins, bhai kuch minute pehle!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_30',
    question: '4 pair subah, 2 dopahar, 3 raat?',
    options: ['Jaanwar', 'Insaan crawl-walk-cane', 'Robot', 'Spider'],
    correctIndex: 1,
    explanation: 'Sphinx ka famous riddle - Insaan!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_31',
    question: 'Match, candle, lamp - pehle kya jalaoge?',
    options: ['Candle', 'Lamp', 'Match', 'Sab saath'],
    correctIndex: 2,
    explanation: 'Match bina kuch nahi jal sakta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_32',
    question: 'Koi end nahi hota?',
    options: ['Rassi', 'Circle', 'Road', 'Wall'],
    correctIndex: 1,
    explanation: 'Circle ka end nahi hota!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_33',
    question: '100 mein kitne birthday nahi manate?',
    options: ['0', '1', '50', '100'],
    correctIndex: 0,
    explanation: 'Sab manate hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_34',
    question: 'Truck 3 driver, parked hai. Kyu nahi chal raha?',
    options: ['Petrol khatam', 'Khada hai', 'Driver gayab', 'Kharab hai'],
    correctIndex: 1,
    explanation: 'Truck simply parked hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ha_35',
    question: 'Building 5 manzil, lift se sirf 1 jaaye, kyu?',
    options: ['Chhota hai', 'Lift kharab', 'Pasand', 'Sasta hai'],
    correctIndex: 0,
    explanation: 'Button tak haath nahi pahunchta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.hard,
  ),
  Question(
    id: 'ex_1',
    question: 'Bolne se badhe, na bolne se ghate?',
    options: ['Awaaz', 'Reputation', 'Vishwas', 'Gussa'],
    correctIndex: 1,
    explanation: 'Reputation baat karne se phailta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_2',
    question: '5 aadmi 5 deewar kitne min mein?',
    options: ['25', '5', '1', '10'],
    correctIndex: 1,
    explanation: 'Sab parallel kaam karte, time same!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_3',
    question: 'Khud apni chhaya nahi banata?',
    options: ['Insaan', 'Bhoot', 'Ped', 'Jaanwar'],
    correctIndex: 1,
    explanation: 'Bhoot ka physical body nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_4',
    question: 'Apne hi ghar mein chor pakda gaya?',
    options: ['Khud chor tha', 'Dusre ghar gaya', 'Sapna tha', 'Police bula li'],
    correctIndex: 0,
    explanation: 'Khud kisi aur ke ghar gaya tha!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_5',
    question: 'Shuruaat nahi, end hota hai?',
    options: ['Circle', 'Maut', 'Kahani', 'Gyaan'],
    correctIndex: 1,
    explanation: 'Maut definite end hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_6',
    question: 'Last wale ko overtake karo, kya banoge?',
    options: ['First', 'Last', 'Second Last', 'Impossible'],
    correctIndex: 3,
    explanation: 'Last ko overtake nahi kar sakte!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_7',
    question: '2 letters wali language?',
    options: ['Hindi', 'Morse Code', 'English', 'Spanish'],
    correctIndex: 1,
    explanation: 'Dots aur dashes!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_8',
    question: 'Zyada kamata, phir bhi gareeb?',
    options: ['Kanjoos hai', 'Pados ameer hai', 'Karz mein', 'Sab false'],
    correctIndex: 1,
    explanation: 'Relatively gareeb lagega!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_9',
    question: 'Zyada bolne wale ko sabse kam pata?',
    options: ['Gossip', 'Gyaan', 'Jhooth', 'Kahaani'],
    correctIndex: 1,
    explanation: 'Expert quiet rehte hain!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_10',
    question: '2 guards, ek sach ek jhooth. Konsa sawal?',
    options: ['Dono se pucho', 'Jhoothe se ulta pucho', 'Sikka uchhalo', 'Pata nahi'],
    correctIndex: 1,
    explanation: 'Jhoothe se pucho, ulta jawab milega!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_11',
    question: 'Use ke baad doosri jagah jaaye, khud wahi rahe?',
    options: ['Seedhi', 'Pul', 'Darwaza', 'Khidki'],
    correctIndex: 0,
    explanation: 'Seedhi se tum upar jaate, woh wahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_12',
    question: 'Hotel bill split, 1 rupaya kahan gaya?',
    options: ['Manager le gaya', 'Galat tarika jodne ka', 'Bellboy chupaya', 'Sab sahi'],
    correctIndex: 1,
    explanation: 'Math trick - galat addition!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_13',
    question: 'Mehnat na lage, khatam na ho?',
    options: ['Paisa', 'Samay', 'Pyaar', 'Gyaan'],
    correctIndex: 1,
    explanation: 'Samay jab tak zinda ho!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_14',
    question: 'Khud kahe main hamesha jhooth bolta - sach?',
    options: ['Sach', 'Jhooth', 'Paradox', 'Pata nahi'],
    correctIndex: 2,
    explanation: 'Liar paradox - dono nahi ban sakta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_15',
    question: 'Khud ki gravity se bhaari ho jaaye?',
    options: ['Black Hole', 'Star', 'Planet', 'Moon'],
    correctIndex: 0,
    explanation: 'Black hole bahut dense hota!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_16',
    question: 'Doobne wala bach gaya, bachane wala doob gaya?',
    options: ['Expert nahi tha', 'Doobne wala tairna jaanta tha', 'Confusion', 'Dono bache'],
    correctIndex: 1,
    explanation: 'Twist - usse tairna aata tha!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_17',
    question: 'Sabse tez, kabhi thake nahi?',
    options: ['Roshni', 'Sound', 'Wind', 'Time'],
    correctIndex: 0,
    explanation: 'Light kabhi thakti nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_18',
    question: '5 machine 5 min mein 100 cheez kaise?',
    options: ['100', '5', '20', '1'],
    correctIndex: 1,
    explanation: 'Same ratio, 5 hi kaafi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_19',
    question: 'Khaali hokar bhi bhari lage?',
    options: ['Glass', 'Khaali dimaag', 'Bottle', 'Box'],
    correctIndex: 1,
    explanation: 'Confusion mein dimaag bhaari lagta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_20',
    question: 'Room 39 ke saath body mili - 39 kya?',
    options: ['Umar', 'Room number', 'Log', 'Ghante'],
    correctIndex: 1,
    explanation: 'Context-dependent mystery riddle!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_21',
    question: 'Sabko jode, khud akela rahe?',
    options: ['Pul', 'Road', 'Rope', 'Wire'],
    correctIndex: 0,
    explanation: 'Pul beech mein akela khada!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_22',
    question: 'Earth ghoomna band kare, pehle kya hoga?',
    options: ['Sab girenge', 'Atmosphere udd jayega', 'Raat-din rukenge', 'Same rahega'],
    correctIndex: 1,
    explanation: 'Spin se atmosphere bhi ghoomti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_23',
    question: 'Khud ke against fight kare?',
    options: ['Dimaag', 'Immune system', 'Dono sahi', 'Koi nahi'],
    correctIndex: 2,
    explanation: 'Autoimmune mein body khud fight karti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_24',
    question: 'Khud se multiply kar khud hi aaye?',
    options: ['0 ya 1', 'Sirf 1', 'Sirf 0', 'Koi nahi'],
    correctIndex: 0,
    explanation: '0x0=0, 1x1=1!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_25',
    question: 'Present mein nahi, past-future dono mein?',
    options: ['Samay', 'Kal shabd', 'Yaadein', 'Sapne'],
    correctIndex: 1,
    explanation: 'Hindi mein Kal dono ke liye!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_26',
    question: 'Chand par jump, kitna upar jaoge?',
    options: ['Same', '6 guna zyada', 'Neeche giroge', 'Float karoge'],
    correctIndex: 1,
    explanation: 'Moon gravity 1/6 hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_27',
    question: 'Sabse powerful, kabhi dikhe nahi?',
    options: ['Gravity', 'Pyaar', 'Vichar', 'Sabhi'],
    correctIndex: 3,
    explanation: 'Teeno invisible par powerful!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_28',
    question: 'Train mein gend upar, kahan giregi?',
    options: ['Peeche', 'Same haath', 'Aage', 'Bahar'],
    correctIndex: 1,
    explanation: 'Inertia se same jagah aayegi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_29',
    question: 'Kabhi na ruke, koi dekhe na dekhe?',
    options: ['Ghadi', 'Samay', 'Dil', 'Saans'],
    correctIndex: 1,
    explanation: 'Samay kabhi nahi rukta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_30',
    question: 'Aadha bhara, aadha khaali. Kya darshata?',
    options: ['Math error', 'Nazariya', 'Confusion', 'Trick'],
    correctIndex: 1,
    explanation: 'Optimist vs pessimist soch!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_31',
    question: 'Sabse chhoti, sabse bada impact?',
    options: ['Atom', 'Virus', 'Vichar', 'Sabhi'],
    correctIndex: 3,
    explanation: 'Teeno chhote, bada impact!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_32',
    question: 'Infinite baar half karo, kabhi zero hoga?',
    options: ['Haan', 'Mathematically kabhi nahi', 'Pata nahi', 'Depends'],
    correctIndex: 1,
    explanation: 'Zeno paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_33',
    question: 'Purani hoke bhi roz nayi lage?',
    options: ['Suraj', 'Chand', 'Dono', 'Koi nahi'],
    correctIndex: 2,
    explanation: 'Suraj-chand roz naye lagte!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_34',
    question: 'Khud kahe yeh statement jhooth hai - sach/jhooth?',
    options: ['Sach', 'Jhooth', 'Paradox', 'Dono'],
    correctIndex: 2,
    explanation: 'Self-referential paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'ex_35',
    question: 'Bina move kiye sabse zyada cover kare?',
    options: ['Road', 'Time', 'River', 'Rotation'],
    correctIndex: 1,
    explanation: 'Samay khud move nahi karta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.expert,
  ),
  Question(
    id: 'in_1',
    question: '3 darwaze, jhoothe guard se ek hi sawal?',
    options: ['Safe darwaza kaunsa', 'Dusra guard kya kahega', 'Sher kahan', 'Aag kahan'],
    correctIndex: 1,
    explanation: 'Ulta jawab milega!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_2',
    question: '2 tribes, ek sach ek jhooth - kaise pehchanno?',
    options: ['Tum kis tribe se ho', 'Tum sach bolne wale ho kya kahoge', 'Doosra kahan hai', 'Jhooth bolte ho'],
    correctIndex: 1,
    explanation: 'Dono se haan jawab milega!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_3',
    question: 'Schrodinger ki billi box mein - state kya hai?',
    options: ['Zinda', 'Mari hui', 'Dono ek saath', 'Pata nahi'],
    correctIndex: 2,
    explanation: 'Superposition mein hoti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_4',
    question: 'Light se tez chale, kya possible hoga?',
    options: ['Kuch nahi', 'Time travel', 'Teleport', 'Sab kuch'],
    correctIndex: 1,
    explanation: 'Einstein ki relativity ka concept!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_5',
    question: 'Statement khud kahe main galat hoon - kya hoga?',
    options: ['Galat banega', 'Sach banega', 'Paradox - dono nahi', 'Matlab nahi'],
    correctIndex: 2,
    explanation: 'Liar paradox - kabhi consistent nahi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_6',
    question: 'Infinite hotel bhara, naya guest aaye, jagah milegi?',
    options: ['Nahi', 'Haan, shift karke', 'VIP ko milegi', 'Naya hotel'],
    correctIndex: 1,
    explanation: 'Hilbert ka Infinite Hotel paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_7',
    question: 'Future se khud milo, kya naya bolega?',
    options: ['Kuch nahi, paradox hoga', 'Predict karega', 'Sab kuch', 'Milna impossible'],
    correctIndex: 0,
    explanation: 'Causality violate hogi!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_8',
    question: '3 darwaze, car ek mein, switch karna chahiye?',
    options: ['Nahi', 'Haan, chance badhta hai', 'Farak nahi', 'Luck pe depend'],
    correctIndex: 1,
    explanation: 'Monty Hall - 2/3 chance!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_9',
    question: 'Infinite universe mein, infinite versions of tum?',
    options: ['Nahi possible', 'Theoretically haan', 'Sirf ek tum', 'Pata nahi'],
    correctIndex: 1,
    explanation: 'Multiverse theory!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_10',
    question: 'Jahaaz ke sab parts badle, wahi jahaaz?',
    options: ['Haan', 'Nahi', 'Paradox - dono valid', 'Depends'],
    correctIndex: 2,
    explanation: 'Ship of Theseus paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_11',
    question: 'Robot tumhare jaisa soche, woh tum ho?',
    options: ['Tum ho', 'Alag entity', 'Philosophical debate', 'Robot soch nahi sakta'],
    correctIndex: 2,
    explanation: 'Consciousness ka deep sawal!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_12',
    question: 'Particles door hote hue connected kaise?',
    options: ['Magic hai', 'Spooky action at distance', 'Light se fast info', 'Fake hai'],
    correctIndex: 1,
    explanation: 'Einstein bhi confused tha isse!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_13',
    question: 'Black hole mein gir jao, time kaisa lagega?',
    options: ['Same', 'Tumhe normal, bahar freeze dikhega', 'Gayab ho jaoge', 'Reverse hoga'],
    correctIndex: 1,
    explanation: 'Gravity time dilate karti hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_14',
    question: 'Dada ko shaadi se pehle roko, kya hoga?',
    options: ['Tum paida nahi hoge', 'Paradox banega', 'Kuch nahi', 'Naya timeline'],
    correctIndex: 1,
    explanation: 'Grandfather paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_15',
    question: 'AI khud ko improve kare exponentially, kya hoga?',
    options: ['Kuch nahi badlega', 'Singularity ho sakti', 'AI rukega', 'Insaan control karenge'],
    correctIndex: 1,
    explanation: 'Technological Singularity theory!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_16',
    question: 'Universe bada hai, aliens kyu nahi mile?',
    options: ['Exist nahi karte', 'Multiple theories hain', 'Sarkar chhupa rahi', 'Bahut chhote hain'],
    correctIndex: 1,
    explanation: 'Fermi Paradox - unsolved hai!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_17',
    question: 'Apne purane self se milo, same vyakti ho?',
    options: ['Same', 'Identity ka philosophical debate', 'Alag vyakti', 'Paradox banega'],
    correctIndex: 1,
    explanation: 'Personal identity over time!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_18',
    question: 'Har decision se naya universe banta hai?',
    options: ['Nahi, ek hi hai', 'Many-Worlds mein haan', 'Sirf badi decisions', 'Fiction hai'],
    correctIndex: 1,
    explanation: 'Quantum mechanics ki theory!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_19',
    question: 'Khud bolo yeh prove nahi ho sakti - sach?',
    options: ['Haan', 'Godel paradox hai', 'Nahi', 'Meaningless hai'],
    correctIndex: 1,
    explanation: 'Incompleteness theorem - math paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_20',
    question: 'Sote waqt consciousness kahan jaata hai?',
    options: ['Khatam hota', 'Science abhi explain nahi kar paayi', 'Dusri jagah jaata', 'Sapno mein'],
    correctIndex: 1,
    explanation: 'Hard Problem of Consciousness!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_21',
    question: 'Random brain bana jo sochta real hai, prove karoge?',
    options: ['Easy hai', 'Impossible to prove definitively', 'Sapna check karo', 'Doosron se pucho'],
    correctIndex: 1,
    explanation: 'Boltzmann Brain thought experiment!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_22',
    question: 'Neuron-by-neuron artificial badlo, kab tum na rahoge?',
    options: ['Pehle neuron se', 'Clear answer nahi hai', 'Last neuron se', 'Kabhi nahi'],
    correctIndex: 1,
    explanation: 'Ship of Theseus jaisa paradox!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_23',
    question: 'Big Bang se pehle kya tha?',
    options: ['Kuch nahi', 'Time hi shuru hua tabhi', 'Doosra universe', 'Pata nahi'],
    correctIndex: 1,
    explanation: 'Time khud Big Bang se shuru!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_24',
    question: 'Khud ko prove karo exist karte ho, kaise?',
    options: ['Circular reasoning hai', 'Sochna hi proof hai', 'Zaroori nahi', 'Impossible hai'],
    correctIndex: 1,
    explanation: 'Descartes - I think therefore I am!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_25',
    question: '2 parallel brahmand mein time same speed?',
    options: ['Haan hamesha', 'Alag bhi ho sakta', 'Time hota hi nahi', 'Impossible'],
    correctIndex: 1,
    explanation: 'Different physics laws ho sakte!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_26',
    question: 'Solution verify karna easy, solve karna bhi easy?',
    options: ['Computers fast hain', 'P vs NP problem hai', 'AI insaan banega', 'Internet bada hai'],
    correctIndex: 1,
    explanation: 'Million-dollar unsolved problem!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_27',
    question: 'Infinite monkeys typewriter pe, Shakespeare likhenge?',
    options: ['Kabhi nahi', 'Theoretically haan', 'Sirf insaan likh sakte', 'Depends'],
    correctIndex: 1,
    explanation: 'Infinite Monkey Theorem!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_28',
    question: 'Dark matter kabhi dekha nahi, pata kaise chala?',
    options: ['Guess hai', 'Gravitational effects se infer', 'Telescope se dikhta', 'Fake hai'],
    correctIndex: 1,
    explanation: 'Galaxy rotation se evidence milta!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_29',
    question: 'Quantum computer normal se kitna fast?',
    options: ['Same speed', 'Exponentially fast kuch problems mein', '2x fast', 'Slower hota'],
    correctIndex: 1,
    explanation: 'Factorization jaisi problems mein speedup!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_30',
    question: 'Original parts se naya jahaaz, asli kaunsa?',
    options: ['Pehla wala', 'Dusra wala', 'Dono asli - unclear', 'Koi nahi'],
    correctIndex: 2,
    explanation: 'Identity ki definition challenge hoti!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_31',
    question: 'Simulation mein reh rahe ho, pata chal sakta?',
    options: ['Haan easily', 'Prove karna mushkil hai', 'Nahi kabhi', 'Already pata hai'],
    correctIndex: 1,
    explanation: 'Simulation Hypothesis - serious theory!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_32',
    question: 'Universe laws aise hain ki hum exist kare?',
    options: ['Universe humare liye bana', 'Selection bias hai', 'Religion ka concept', 'Random hai'],
    correctIndex: 1,
    explanation: 'Anthropic Principle!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_33',
    question: 'Entropy hamesha badhe, universe ka end kya?',
    options: ['Phat jayega', 'Heat Death hoga', 'Shrink hoga', 'Kuch nahi'],
    correctIndex: 1,
    explanation: 'Maximum entropy pe pahunchega!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_34',
    question: 'Quantum mein hidden variables nahi hote, matlab?',
    options: ['QM galat hai', 'Reality probabilistic hai', 'Predetermined hai', 'Sirf theory'],
    correctIndex: 1,
    explanation: 'Bell ke Theorem ne prove kiya!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'in_35',
    question: 'Future ko message bhejo jo present change kare?',
    options: ['Bhej diya jayega', 'Bootstrap Paradox banega', 'Impossible hai', 'Resolve hoga'],
    correctIndex: 1,
    explanation: 'Causal loop bina origin ke!',
    category: GameCategory.brainTrap,
    difficulty: Difficulty.insane,
  ),
  Question(
    id: 'lg1',
    question: 'All Bloops are Razzles, Razzles are Lazzles. Bloops Lazzles?',
    options: ['Yes', 'No', 'Maybe', 'Cannot say'],
    correctIndex: 0,
    explanation: 'Bloops to Razzles to Lazzles - so yes!',
    category: GameCategory.logic,
    difficulty: Difficulty.medium,
  ),
  Question(
    id: 'lg2',
    question: 'What comes next: 2, 4, 8, 16, ?',
    options: ['24', '32', '18', '20'],
    correctIndex: 1,
    explanation: 'Each number doubles!',
    category: GameCategory.logic,
    difficulty: Difficulty.easy,
  ),
  Question(
    id: 'mm1',
    question: 'Which color is in BOTH Indian and French flag?',
    options: ['Green', 'Orange', 'Blue', 'White'],
    correctIndex: 3,
    explanation: 'White appears in both!',
    category: GameCategory.memory,
    difficulty: Difficulty.easy,
  ),
];

List<Question> getQuestions(GameCategory category, Difficulty difficulty) {
  var filtered = _allQuestions
      .where((q) => q.category == category && q.difficulty == difficulty)
      .toList();

  // Fallback only if truly empty for this category+difficulty
  if (filtered.isEmpty) {
    filtered = _allQuestions.where((q) => q.category == category).toList();
  }

  filtered.shuffle();
  return filtered.take(5).toList();
}

// Game State
class GameState {
  final List<Question> questions;
  final int currentIndex;
  final int score;
  final int correct;
  final int wrong;
  final int timeLeft;
  final bool answered;
  final int? selectedIndex;
  final bool isFinished;

  const GameState({
    required this.questions,
    this.currentIndex = 0,
    this.score = 0,
    this.correct = 0,
    this.wrong = 0,
    this.timeLeft = 30,
    this.answered = false,
    this.selectedIndex,
    this.isFinished = false,
  });

  Question? get currentQuestion =>
      currentIndex < questions.length ? questions[currentIndex] : null;

  GameState copyWith({
    int? currentIndex,
    int? score,
    int? correct,
    int? wrong,
    int? timeLeft,
    bool? answered,
    int? selectedIndex,
    bool? isFinished,
  }) {
    return GameState(
      questions: questions,
      currentIndex: currentIndex ?? this.currentIndex,
      score: score ?? this.score,
      correct: correct ?? this.correct,
      wrong: wrong ?? this.wrong,
      timeLeft: timeLeft ?? this.timeLeft,
      answered: answered ?? this.answered,
      selectedIndex: selectedIndex ?? this.selectedIndex,
      isFinished: isFinished ?? this.isFinished,
    );
  }
}

class GameNotifier extends StateNotifier<GameState> {
  Timer? _timer;
  final Difficulty difficulty;
  final DateTime _startTime = DateTime.now();

  GameNotifier({required List<Question> questions, required this.difficulty})
    : super(GameState(questions: questions, timeLeft: difficulty.timeLimit)) {
    _startTimer();
  }

  void _startTimer() {
    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (state.answered) return;
      if (state.timeLeft <= 0) {
        _timeUp();
      } else {
        state = state.copyWith(timeLeft: state.timeLeft - 1);
      }
    });
  }

  void _timeUp() {
    state = state.copyWith(answered: true, wrong: state.wrong + 1);
    Future.delayed(const Duration(seconds: 2), nextQuestion);
  }

  void answerQuestion(int index) {
    if (state.answered) return;
    final question = state.currentQuestion;
    if (question == null) return;

    final isCorrect = index == question.correctIndex;
    final points = isCorrect
        ? (state.timeLeft * difficulty.pointsMultiplier * 10)
        : 0;

    // Play sound
    if (isCorrect) {
      print('Playing correct sound');
      audioManager.playCorrect();
    } else {
      print('Playing wrong sound');
      audioManager.playWrong();
    }

    state = state.copyWith(
      answered: true,
      selectedIndex: index,
      score: state.score + points,
      correct: isCorrect ? state.correct + 1 : state.correct,
      wrong: isCorrect ? state.wrong : state.wrong + 1,
    );

    Future.delayed(const Duration(seconds: 2), nextQuestion);
  }

  void nextQuestion() {
    if (state.currentIndex + 1 >= state.questions.length) {
      _timer?.cancel();
      state = state.copyWith(isFinished: true);
      return;
    }
    state = state.copyWith(
      currentIndex: state.currentIndex + 1,
      timeLeft: difficulty.timeLimit,
      answered: false,
      selectedIndex: null,
    );
  }

  GameResult getResult() {
    return GameResult(
      score: state.score,
      correct: state.correct,
      wrong: state.wrong,
      total: state.questions.length,
      timeTaken: DateTime.now().difference(_startTime),
      difficulty: difficulty,
      category: state.questions.first.category,
    );
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
}

final gameProvider =
    StateNotifierProvider.family<GameNotifier, GameState, Map<String, dynamic>>(
      (ref, params) {
        return GameNotifier(
          questions: params['questions'] as List<Question>,
          difficulty: params['difficulty'] as Difficulty,
        );
      },
    );
