// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAul7C_TZI_xhda1cM9EcsvnwV6L318U4g',
    appId: '1:999213489105:web:a720ed7a3c24cd684cdef0',
    messagingSenderId: '999213489105',
    projectId: 'chakkar-9695a',
    authDomain: 'chakkar-9695a.firebaseapp.com',
    storageBucket: 'chakkar-9695a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-t_eNw1TTc1Ch3Tc2yM2B8pzOAyKYrn8',
    appId: '1:999213489105:android:2b3de38c6bd36c034cdef0',
    messagingSenderId: '999213489105',
    projectId: 'chakkar-9695a',
    storageBucket: 'chakkar-9695a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDff50Xntlve6_VoH1fwf4NeJqyoCVpnQ8',
    appId: '1:999213489105:ios:d586f761c0fa28a54cdef0',
    messagingSenderId: '999213489105',
    projectId: 'chakkar-9695a',
    storageBucket: 'chakkar-9695a.firebasestorage.app',
    iosBundleId: 'com.chakkar.chakkar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDff50Xntlve6_VoH1fwf4NeJqyoCVpnQ8',
    appId: '1:999213489105:ios:d586f761c0fa28a54cdef0',
    messagingSenderId: '999213489105',
    projectId: 'chakkar-9695a',
    storageBucket: 'chakkar-9695a.firebasestorage.app',
    iosBundleId: 'com.chakkar.chakkar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAul7C_TZI_xhda1cM9EcsvnwV6L318U4g',
    appId: '1:999213489105:web:8f5149dd4fa4c6eb4cdef0',
    messagingSenderId: '999213489105',
    projectId: 'chakkar-9695a',
    authDomain: 'chakkar-9695a.firebaseapp.com',
    storageBucket: 'chakkar-9695a.firebasestorage.app',
  );
}
